### ISSUE TITLE
Merged Vladimir's commits

### ISSUE THREAD

**Issue by jonasswiatek** [jonasswiatek/strokes#5] opened 2011-10-04 22:22 UTC
Okey, I couldn't keep my clammy hands away from all the fancy Fork Queue stuff - and I've merged Vlad's changes so far. I THINK it went well (I had to switch to the actual git client to get some of the changes down).

If it worked, then git is some fucking awesome shit, considering it merged without any merge errors - but if you could all take a short look at it, and see if something is fucked up - the project compiles, works and seems to have a sense of select Danish, Dutch and Russian language now.

**Comment by vlad2135** [comment] 2011-10-04 22:29
oh, cool, I'll push latest translations (god there is a lot of text :-/) right now and re-check whole solution for errors and leave a comment here.

**Comment by jonasswiatek** [comment] 2011-10-04 22:29
Vlad: you need to do a pull an upstream pull/merge or whatever git calls it (git pull [remotename] master) so you get synched with this repo again.

**Comment by vlad2135** [comment] 2011-10-04 22:44
Yes, I think I've done it. Slowly learning the git way, one painful step at a time...

**Comment by vlad2135** [comment] 2011-10-04 23:00
Well, yes, it looks like solution works and my changes are working too, but I have a problem - I can not build solution in Release\AnyCPU (but Debug\AnyCPU works!). 

Build fails at Strokes.GUI project:
Error   1   NotifyPropertyWeaver: Unhandled exception occurred System.IO.FileNotFoundException: Could not find file 'C:\Users\Vlad\Documents\Zork\Strokes\strokes.vlad2135\source\Strokes.GUI\obj\Release\Strokes.GUI.pdb'.
File name: 'C:\Users\Vlad\Documents\Zork\Strokes\strokes.vlad2135\source\Strokes.GUI\obj\Release\Strokes.GUI.pdb'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Mono.Cecil.Pdb.PdbReaderProvider.GetSymbolReader(ModuleDefinition module, String fileName)
   at Mono.Cecil.ModuleReader.ReadSymbols(ModuleDefinition module, ReaderParameters parameters)
   at Mono.Cecil.ModuleReader.CreateModuleFrom(Image image, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(Stream stream, ReaderParameters parameters)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at WeavingCommon.ModuleReader.Execute()
   at NotifyPropertyWeaverMsBuildTask.WeavingTask.Inner()
   at NotifyPropertyWeaverMsBuildTask.WeavingTask.Execute() Strokes.GUI

Sorry, don't have time for git bisect now, so I can't tell if it was always here or appeared because of my changes or x86/AnyCPU confusion (caused by me).

**Comment by jonasswiatek** [comment] 2011-10-04 23:16
Try to do a project clean and rebuild, and then make sure it's set to debug and not release in visual studio. This just sounds like everyday Visual Studio strangeness to me

**Comment by jonasswiatek** [comment] 2011-10-05 00:03
Okey, I didn't properly read your error description. I've solved this issue - there were some settings in Strokes.GUI that had gone haywire.

As a nice bonus, the build script now copies the .vsix file into /build-output/{Debug,Release} so it's easily accessible if you'd need it.

Can you verify that it works on your end?

**Comment by clausjoergensen** [comment] 2011-10-05 15:02
The pdb, like any other binary content, isn't checked in.

**Closed as completed by clausjoergensen** 2011-10-05 15:02 UTC
Labels: Info
